### ISSUE TITLE
Linux problem with npm install

### ISSUE THREAD

**Issue by Andyroid1978** [nulltask/node-three.js#4]
I'm not sure this is right place for my issue, buti landed here from npmjs.org so maybe it is.

Anyway i run nodejs v0.10.25 in a linux mint 16 machine and if i try to include three.js in a script i get the following error:

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/andy/Lavori/OB_Works/alcas/Symfony/scripts/node_modules/three.js/lib/../deps/three.js/build/Three.js'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/home/andy/Lavori/OB_Works/alcas/Symfony/scripts/node_modules/three.js/lib/three.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/andy/Lavori/OB_Works/alcas/Symfony/scripts/node_modules/three.js/index.js:2:18)

```

After an investigation, i found out that the problem is a wrong case inside the file `lib/three.js`: it should be `three.js` instead of `Three.js` when including the path at line 9.

Please, fix it in the npm installation module. Thanks.

**Comment by Pegase745** [comment]
+1 to @nulltask , could it possibly be updated on NPM to solve this error? Thanks in advance

**Comment by KashinMax** [comment]
Hi, @Pegase745  try using "three.js": "git+https://github.com/nulltask/node-three.js.git#master" in your package.json to install this module directly from this github repository. That works for me, hope it will help.

**Comment by Pegase745** [comment]
Thx, I'll do that for now :)
